import React from "react";

const HomeAbout = () => {
  return (
    <div
      className="container my-5"
      style={{ display: "flex", flexDirection: "column", alignItems: "center" }}
    >
      <h3>ABOUT US</h3>

      <p className="my-2">
        IEEE IS THE WORLD'S LARGEST TECHNICAL PROFESSIONAL ORGANIZATION
        DEDICATED TO ADVANCING TECHNOLOGY FOR THE BENEFIT OF HUMANITY. IEE AIMS
        TO SERVE PROFESSIONALS INVOLVED IN ALL ASPECTS OF THE ELECTRICAL,
        ELECTRONI9CS AND COMPUTING FIELDS AND RELATED AREAS OF SCIENCE AND
        TECHNOLOGY WITH THE NECESSARY RESOURCES FOR THE PROGRESSION OF MODERN
        CIVILIZATION. THE IEEE BODY APPROVED THE FORMATION OF THE IEEE
        NANOTECHNOLOGY COUNCIL AND ITS FIELD OF INTEREST ON FEBRUARY 17, 2022.
        THE IEEE NANOTECHNOLOGY COUNCIL SUPPORTS THE ADVANCEMENT AND
        COORDINATION OF WORKS IN THE FIELD OF NANOTECHNOLOGY BY SUPPORTING THE
        THEORY, DESIGN AND DEVELOPMENT OF NANOTECHNOLOGY AND ITS SCIENTIFIC,
        ENGINEERING, AND INDUSTRIAL APPLICATION. THE IEEE NANOTECHNOLOGY COUNCIL
        IS PART OF THE DIVISION- CIRCUITS AND DEVICES AND IS MADE UP OF 23
        MEMBER SOCIETIES AND HAS MANY CHAPTERS. IN THIS STUDENT CHAPTER, WE AT
        IIT PATNA IS TRYING TO CREATE AN INTERACTIVE PLATFORM FOR THE STUDENT
        MEMBERS TO DISCUSS AND COLLABORATE WITH THE ACADEMICIANS AND INDUSTRY
        PROFESSIONAL WHO ARE WORKING IN THE NANOTECHNOLOGY FIELD. FURTHER, THE
        IEEE NTC STUDENT CHAPTER COVERS A VAST VARIETY OF TOPICS CONSISTING OF
        PHOTONICS, OPTOELECTRONICS, PHOTOVOLTAIC, MEMRISTIVE TECHNOLOGIES, THE
        INTERNET OF THINGS, AND SO ON. THE MAJOR AIM OF THIS STUDENT CHAPTER IS
        TO DEVELOP THE YOUNG PROFESSIONALS TOWARDS THE RECENT DEVELOPMENT IN
        NANOTECHNOLOGY AND UTILIZE THERE SKILLS FOR THE WELFARE OF SOCIETY AND
        HUMANITY.
      </p>
    </div>
  );
};

export default HomeAbout;
